#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
cat > "/etc/rc.local" << _EOF_
# Make sure to disable Linux kernel feature transparent huge pages,
# it will affect greatly both memory usage and latency in a negative way.
# See: http://docs.mongodb.org/manual/tutorial/transparent-huge-pages/
if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
  echo never > /sys/kernel/mm/transparent_hugepage/defrag
fi
if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
  echo never > /sys/kernel/mm/transparent_hugepage/enabled
fi

exit \$?

_EOF_

# see http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/
#apt-key adv --keyserver keyserver.ubuntu.com:80 --recv 7F0CEB10
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
apt-get update

apt-get install -y mongodb-org=${DATASTORE_VERSION:-2.6.1}

#mongodb-org-server=${DATASTORE_VERSION:-2.6.1} mongodb-org-shell=${DATASTORE_VERSION:-2.6.1} mongodb-org-mongos=${DATASTORE_VERSION:-2.6.1} mongodb-org-tools=${DATASTORE_VERSION:-2.6.1} -qy

sed -i '/bind_ip/d' /etc/mongod.conf
sed -i '/smallfiles/d' /etc/mongod.conf
echo 'smallfiles = true' >> /etc/mongod.conf