#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

apt-get -y install python-dev libxml2-dev libxslt1-dev python-setuptools python-pip python-sqlalchemy python-lxml \
    python-routes python-eventlet python-webob python-pastedeploy python-paste python-netaddr \
    python-httplib2 python-iso8601 python-pexpect python-mysqldb python-migrate git language-pack-en \
    python-software-properties libevent-dev build-essential mysql-client libmysqlclient-dev python-imaging
