#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive


apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
apt-get update

apt-get install -y mongodb-org=${DATASTORE_VERSION:-2.6.1} mongodb-org-server=${DATASTORE_VERSION:-2.6.1} mongodb-org-shell=${DATASTORE_VERSION:-2.6.1} mongodb-org-mongos=${DATASTORE_VERSION:-2.6.1} mongodb-org-tools=${DATASTORE_VERSION:-2.6.1} -qy
