#!/bin/bash

set -e
set -o xtrace

export HOME="/home/trove"

wget -P /tmp/ https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
python /tmp/ez_setup.py
wget -P /tmp/ https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python /tmp/get-pip.py

mkdir -p ${HOME}/trove; cd ${HOME}/trove
git init; git pull ${TROVE_REMOTE_REPO:-https://github.com/openstack/trove} ${TROVE_REMOTE_REPO_BRANCH:-master}
python setup.py install
cd ~
