#!/bin/bash

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
#apt-get update && apt-get -y dist-upgrade
apt-get -qy install trove-guestagent

sed -i 's/\/etc\/trove\/trove\.conf/\/etc\/trove\/trove\-guestagent\.conf\ \-\-config-file\=\/etc\/guest\_info/g' /etc/init/trove-guestagent.conf
adduser trove sudo
sudo chmod 0755 /etc/trove/conf.d/guest_info.conf
sudo chown trove:trove /etc/trove/conf.d/guest_info.conf
cp -p /etc/trove/conf.d/guest_info.conf /etc/guest_info
chown -R trove:trove /var/log/trove
#service trove-guestagent start
