#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install percona-toolkit percona-server-common-${DATASTORE_VERSION:-5.6} \
    percona-server-server-${DATASTORE_VERSION:-5.6} percona-server-test-${DATASTORE_VERSION:-5.6} \
    percona-server-client-${DATASTORE_VERSION:-5.6} percona-xtrabackup
