#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

#yum install -y mongodb mongodb-server

echo "[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1" | sudo tee -a /etc/yum.repos.d/mongodb.repo

yum install -y  mongo-10gen mongo-10gen-server
usermod -a -G mongod mongod
sudo mkdir -p /var/log/mongodb
touch /var/log/mongodb/mongodb.log
sudo chown -R mongod:mongod /var/log/mongodb

TEMPFILE="mktemp_mongod"
echo "mongod ALL=(ALL) NOPASSWD:ALL" > $TEMPFILE
chmod 0440 $TEMPFILE
sudo chown root:root $TEMPFILE
sudo mv $TEMPFILE /etc/sudoers.d/70_mongod_user
#adduser mongod sudo


