#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install percona-toolkit percona-server-common-${DATASTORE_VERSION:-5.6} \
    percona-server-server-${DATASTORE_VERSION:-5.6} percona-server-test-${DATASTORE_VERSION:-5.6} \
    percona-server-client-${DATASTORE_VERSION:-5.6} percona-xtrabackup

# Bind MySQL service to all network interfaces.
sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf

#set enable InnoDB, UTF-8character set, and UTF-8 collation by default
sed -i "/bind-address/a\default-storage-engine = innodb\n\
collation-server = utf8_general_ci\n\
init-connect = 'SET NAMES utf8'\n\
character-set-server = utf8" /etc/mysql/my.cnf

cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
[mysqld]
performance_schema = off
_EOF_