#!/bin/sh

set -e
set -o xtrace

apt-get install libreadline-dev zlib1g-dev flex bison docbook docbook-dsssl docbook-xsl openjade1.3 xsltproc opensp -qy


wget http://sourceforge.net/projects/postgres-xl/files/Releases/Version_${DATASTORE_VERSION:-9.2}rc/postgres-xl-v${DATASTORE_VERSION:-9.2}-src.tar.gz
gunzip postgres-xl-v${DATASTORE_VERSION:-9.2}-src.tar.gz
tar xf postgres-xl-v${DATASTORE_VERSION:-9.2}-src.tar

cd postgres-xl/
./configure
make
make install
cd contrib/pgxc_ctl
make
make install

ln -s /usr/local/pgsql/bin/* /usr/local/bin/

su postgres -c "pgxc_ctl prepare"
