#!/bin/bash

set -e
set -o xtrace

if [ "${DISTRO}" != "ubuntu" ]; then
    # Copy service file
    dd if=/tmp/in_target.d/openstack-trove-guestagent.service of=/usr/lib/systemd/system/openstack-trove-guestagent.service

    # Configuring permissions
    chown trove:trove /etc/trove
    chown trove:trove /usr/share/trove
    chown trove:trove /var/log/trove
    sudo mv /etc/trove/guest_info /etc/guest_info
    sudo chmod 0755 /etc/guest_info
    chown trove:trove /etc/guest_info
    mkdir -p /etc/trove/conf.d
    sudo cp /etc/guest_info /etc/trove/conf.d/guest_info.conf
    echo '[DEFAULT]' > /etc/trove/conf.d/trove-guestagent.conf
    chown -R trove:trove /etc/trove/conf.d
    # Enable and start service
    systemctl enable openstack-trove-guestagent.service
    systemctl start openstack-trove-guestagent.service
fi
