#!/bin/bash

set -e
set -o xtrace

install-packages augeas-tools openssh-server openssh-client

augtool -s set /files/etc/ssh/sshd_config/GSSAPIAuthentication no
augtool -s set /files/etc/ssh/sshd_config/UseDNS no
augtool -s set /files/etc/ssh/sshd_config/PermitTunnel yes

# ssh-client configuration
# Common
augtool -s set /files/etc/ssh/ssh_config/Host/StrictHostKeyChecking no
augtool -s set /files/etc/ssh/ssh_config/Host/GSSAPIAuthentication no

export GUEST_ACCESS_KEYS="/home/trove/.ssh"

mkdir -p ${GUEST_ACCESS_KEYS}

install -D -g trove -o trove -m 0600 $(dirname $0)/authorized_keys ${GUEST_ACCESS_KEYS}/
