#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive

sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections -v -c
sudo apt-get -qy install python-software-properties debconf-utils
sudo add-apt-repository ppa:webupd8team/java
apt-get update
sudo apt-get  install oracle-java8-installer
sudo apt-get -qy install libjna-java

