#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive


apt-get install -qy curl
echo "deb http://debian.datastax.com/community stable main" >> /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
apt-get update
apt-get install cassandra=${DATASTORE_VERSION:-2.1.1} -qy
service cassandra stop
rm -rf /var/lib/cassandra/data/system/*
service cassandra start
