#!/bin/bash

set -ex
set -o xtrace

export DEBIAN_FRONTEND=noninteractive


apt-get install -qy curl
sudo tee /etc/apt/sources.list.d/cassandra.sources.list <<_EOF_
deb http://www.apache.org/dist/cassandra/debian 21x main
deb-src http://www.apache.org/dist/cassandra/debian 21x main
_EOF_

# add apache cassandra keys
gpg --keyserver keyserver.ubuntu.com --recv-keys 4BD736A82B5C1B00
gpg --export --armor 4BD736A82B5C1B00 | sudo apt-key add -
gpg --keyserver keyserver.ubuntu.com --recv-keys F758CE318D77295D
gpg --export --armor F758CE318D77295D | sudo apt-key add -

apt-get update

apt-get install -qy expect python-dev
apt-get install -qy libxml2-dev ntp mc
apt-get install -qy libxslt1-dev python-pexpect
apt-get install -qy python-migrate build-essential

apt-get install cassandra -qy

service cassandra stop
rm -rf /var/lib/cassandra/data
sudo mkdir /var/lib/cassandra/data
sudo chown cassandra:cassandra -R /var/lib/cassandra

service cassandra start
