#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
apt-get -y install libmysqlclient18 mysql-server-${DATASTORE_VERSION:-5.6} mysql-client-${DATASTORE_VERSION:-5.6} percona-xtrabackup
